CRM/urls.py
from django.contrib import admin
from django.urls import path,re_path
from app01 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 登陆
    path('login/', views.login),
    # 验证码
    path('get_valid_img/', views.get_valid_img),
    # 注册
    path('register/', views.register),
    # 基于modelForm的实现的注册功能
    path('model_register/', views.model_register),
    # 访问首页
    path('index/', views.index),
    # 访问公开用户; name 别名
    path('customers/list/', views.Customers.as_view(), name="customers_list"),
    # 访问私有用户
    # path('mycustomers/list/', views.mycustomers, name="mycustomers_list"),
    path('mycustomers/list/', views.Customers.as_view(), name="mycustomers_list"),
    # 添加公共客户
    path('customers/add/', views.AddEditCustomers.as_view(), name="add_customers"),
    # 编辑公共客户, 使用re_path
    re_path('^customers/edit/(\d+)/$', views.AddEditCustomers.as_view(), name="edit_customers"),
    # 删除公共客户, 使用re_path
    re_path('^customers/del/(\d+)/$', views.DelCustomers.as_view(), name="del_customers"),
    # 客户跟踪记录
    path('customers/tracking/', views.TrackCustomers.as_view(), name="track_customers"),
    # 添加客户跟踪记录
    path('track_customers/add/', views.AddEditTrackCustomers.as_view(), name="add_track_customers"),
    # 编辑客户跟踪记录
    re_path('^track_customers/edit/(\d+)/$', views.AddEditTrackCustomers.as_view(), name="edit_track_customers"),
    # 班级跟踪记录
    path('class/study/list/', views.ClassStudyList.as_view(), name="class_study_list"),
    # 班级跟踪记录-添加
    path('class/study/add/', views.AddEditClassStudy.as_view(), name="add_class_study"),
    # 班级跟踪记录-编辑
    re_path('^class/study/edit/(\d+)/$', views.AddEditClassStudy.as_view(), name="add_class_study"),
    # 班级跟踪记录-删除
    re_path('^class/study/del/(\d+)/$', views.DelClassStudy.as_view(), name="del_class_study"),
    # 班级跟踪记录-录入成绩
    re_path('^record/entry/(\d+)/$', views.RecordEntry.as_view(), name="record_entry"),
    # 学生学习记录
    path('student/study/list/', views.StudentStudyList.as_view(), name="student_study_list"),
    # 学生学习记录-添加
    path('student/study/add/', views.AddEditStudentStudy.as_view(), name="add_study_list"),
    # 学生学习记录-编辑
    re_path('student/study/edit/(\d+)/$', views.AddEditStudentStudy.as_view(), name="edit_study_list"),
    # 学生学习记录-删除
    re_path('student/study/del/(\d+)/$', views.DelStudentStudy.as_view(), name="del_study_list"),
    # 统计查询
    path('count_query/', views.CountQueryView.as_view(), name="count_query"),
]

app01/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib import auth
from django.http import JsonResponse
from django import forms
from django.forms import widgets as wid
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.db.models import Q
from django.urls import reverse
from django.views import View
from django.forms.models import modelformset_factory
from django.db.models import Count

import random
import re
import datetime

from app01.models import UserInfo, Customer, ConsultRecord, ClassStudyRecord, StudentStudyRecord, Student
from app01.page import Pagination

# Create your views here.
# ========== 原始基于forms组件的注册 ==========
# 注册
class UserForm(forms.Form):
    username = forms.CharField(max_length=32, label="用户名")
    password = forms.CharField(min_length=3, max_length=32, label="密码", widget=wid.PasswordInput())
    r_password = forms.CharField(min_length=3, max_length=32, label="确认密码", widget=wid.PasswordInput())
    email = forms.EmailField(max_length=32, label="邮箱")

    # 统一设置样式
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs.update({'class': 'form-control'})

    # 用户不能重复
    def clean_username(self):
        val = self.cleaned_data.get("username")
        user = UserInfo.objects.filter(username=val).first()
        if user:
            raise ValidationError("用户已存在")
        else:
            return val

    # 密码不能是纯数字
    def clean_password(self):
        val = self.cleaned_data.get("password")
        if val.isdigit():
            raise ValidationError("密码不能是纯数字")
        else:
            return val

    # 邮箱必须是163邮箱
    def clean_email(self):
        val = self.cleaned_data.get("email")
        if re.search("\w+@163.com$", val):
            return val
        else:
            raise ValidationError("邮箱必须是163邮箱")

    # 两次密码不一致
    def clean(self):
        p1 = self.cleaned_data.get("password")
        p2 = self.cleaned_data.get("r_password")
        if p1 and p2 and p1 != p2:
            # 将错误信息直接写入到add_error中, 不用默认的__all__作为键, 使用自定的键, 方便后面的使用,
            # 也不用再对__all__做特殊化处理了(原因,看源码)
            self.add_error("r_password", ValidationError("两次密码不一致"))
            # raise ValidationError("两次密码不一致")
        else:
            return self.cleaned_data

def register(request):
    if request.is_ajax():
        # 绑定数据的表单实例
        form = UserForm(request.POST)
        response = {"username": None, "err_msg": ""}
        if form.is_valid():
            response["username"] = request.POST.get("username")
            username = request.POST.get("username")
            password = request.POST.get("password")
            UserInfo.objects.create_user(username=username, password=password)
        else:
            response["err_msg"] = form.errors
        return JsonResponse(response)
    else:
        form = UserForm()
        return render(request, "register.html", locals())

# ========== 基于modelform的注册 ==========
# 首先需要导入ModelForm类
class UserModelForm(ModelForm):
    class Meta:
        # 与models建立依赖关系
        model = UserInfo
        # 字段，__all__ 表示列出所有字段
        # fields = "__all__"
        fields = ['username', 'password', 'email']
        # 排除的字段
        exclude = None

        # 单独设置每个错误;
        # error_messages 全局设置, 所以加s
        error_messages = {
            "username": {'required': '用户名不能为空', },
            "password": {'required': '密码不能为空', },
            # "r_password": {'r_required': '确认密码不能为空'},
            "email": {'required': '邮件不能为空', },
        }

        labels = {
            "username": "用户名",
            "password": "密码",
            # "r_password": "确认密码",
            "email": "邮件",
        }

        widgets = {
            "password": wid.PasswordInput(),
            # "r_password": wid.PasswordInput(),
        }

    r_password = forms.CharField(min_length=3, max_length=32, label="确认密码", widget=wid.PasswordInput())
    # 统一设置样式
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs.update({'class': 'form-control'})

    # 钩子的用法一致
    # 用户不能重复
    def clean_username(self):
        val = self.cleaned_data.get("username")
        user = UserInfo.objects.filter(username=val).first()
        if user:
            raise ValidationError("用户已存在")
        else:
            return val

    # 密码不能是纯数字
    def clean_password(self):
        val = self.cleaned_data.get("password")
        if val.isdigit():
            raise ValidationError("密码不能是纯数字")
        else:
            return val

    # 邮箱必须是163邮箱
    def clean_email(self):
        val = self.cleaned_data.get("email")
        if re.search("\w+@163.com$", val):
            return val
        else:
            raise ValidationError("邮箱必须是163邮箱")

    # 两次密码不一致
    def clean(self):
        p1 = self.cleaned_data.get("password")
        p2 = self.cleaned_data.get("r_password")
        if p1 and p2 and p1 != p2:
            # 将错误信息直接写入到add_error中, 不用默认的__all__作为键, 使用自定的键, 方便后面的使用,
            # 也不用再对__all__做特殊化处理了(原因,看源码)
            self.add_error("r_password", ValidationError("两次密码不一致"))
            # raise ValidationError("两次密码不一致")
        else:
            return self.cleaned_data

def model_register(request):
    if request.is_ajax():
        # 绑定数据的表单实例
        form = UserModelForm(request.POST)
        response = {"username": None, "err_msg": ""}
        if form.is_valid():
            response["username"] = request.POST.get("username")
            # 添加记录
            form.save()
        else:
            response["err_msg"] = form.errors
        return JsonResponse(response)
    else:
        form = UserModelForm()
        return render(request, "model_register.html", {'form': form})

# 登录
def login(request):
    if request.is_ajax():   # 判断是否是ajax发来的请求，布尔类型true或false
        username = request.POST.get("username")
        password = request.POST.get("password")
        validcode = request.POST.get("validcode")

        # Ajax请求返回一个字典
        response = {"username": None, "err_msg": ""}
        # request.session????????????????????
        if validcode.upper() == request.session.get("keep_str").upper():
            # auth.authenticate 用户认证，验证用户名及密码是否正确；没有返回None
            user_obj = auth.authenticate(username=username, password=password)
            if user_obj:
                response["username"] = username
                #
                auth.login(request, user_obj)
            else:
                response["err_msg"] = "用户名或者密码错误"
        else:
            response["err_msg"] = "验证码错误"
        # JsonResponse 自动将字典序列化, 并设置 Content-Type: application/json
        return JsonResponse(response)
    else:
        return render(request, "login.html")

# 验证码
def get_valid_img(request):
    # 依赖pil模块, 需要安装
    # pip3 install pillow
    from PIL import Image, ImageDraw, ImageFont
    from io import BytesIO

    # 定义三原色的随机值
    def get_random_color():
        return (random.randint(0,255),random.randint(0,255),random.randint(0,255))

    # 获取一个img对象, 参数分别是RGB模式 宽350, 高38, 红色
    img = Image.new("RGB", (350, 38), get_random_color())

    # 获取一个画笔对象, 将图片对象传过去
    draw = ImageDraw.Draw(img)

    # 获取一个font字体对象, 参数是ttf的字体文件路径, 以及字体的大小
    font = ImageFont.truetype("static/font/kumo.ttf", 32)

    # 获取每次循环产生的验证码
    keep_str = ""

    # 生成6位的随机验证码
    for i in range(6):
        # 随机获取数字
        random_num = str(random.randint(0, 9))
        # 随机获取小写字母
        random_lowalf = chr(random.randint(97, 122))
        # 随机获取大写字母
        random_upperalf = chr(random.randint(65, 90))
        # 随机抽取一个值
        random_char = random.choice([random_num, random_lowalf,  random_upperalf])
        # text格式: text(self, xy, text, fill=None, font=None, anchor=None, *args, **kwargs), 看源码
        # 在图片上写东西, 参数是: 定位, 字符串, 颜色, 字体
        draw.text((i*30+80, 0), random_char, get_random_color(), font=font)
        keep_str += random_char

    # 在内存生成图片
    f = BytesIO()
    img.save(f, "png")
    data = f.getvalue()

    # 将验证码存在各自的session中
    request.session['keep_str'] = keep_str

    return HttpResponse(data)

# 首页
def index(request):
    return render(request, "index.html")

# 全部用户+批量删除/公转私
class Customers(View):
    # 查看数据
    def get(self, request):
        # reverse()反向解析，获取customers_list对应的url
        if reverse("customers_list") == request.path:
            label = "公开客户"
            # __isnull 查看销售是否为空,为空的表示公开客户
            customers_list = Customer.objects.filter(consultant__isnull=True)
        else:
            label = "我的客户"
            customers_list = Customer.objects.filter(consultant_id=request.user)

        # val 关键字
        # filed 根据 姓名/QQ/手机 那种类型过滤
        val = request.GET.get("q")
        field = request.GET.get("field")
        if val:
            # Q的实例对象
            q = Q()
            # 里面放元祖
            q.children.append((field + "__contains", val))
            customers_list = Customer.objects.filter(q)

        # 分页
        current_page_num = request.GET.get("page")
        pagination = Pagination(current_page_num, customers_list.count(), request)
        customers_list = customers_list[pagination.start: pagination.end]
        return render(request, "customer_list.html", {"customers_list": customers_list, "pagination": pagination, "label": label})

    # 批量操作
    def post(self, request):
        # 由于要用到反射, 将customers改为CBV的模式
        # func_str 不要和反射的函数名字一样
        func_str = request.POST.get("field")
        # 反射
        if hasattr(self, func_str):
            batch = getattr(self, func_str)
            select_list_pk = request.POST.get("select_list_pk")
            batch(request, select_list_pk)
            # 一定要写返回值, 不能再这里只写self.get(request)
            ret = self.get(request)
            return ret
        else:
            return HttpResponse("非法信息")

    # 批量删除调用的方法(这里是更新的操作, 数据珍贵, 不能随便删除)
    def batch_delet(self, select_list_pk):

templates/add_customer.html
{% extends "base.html" %}
{% block con %}
    <section class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for customer in customer_list %}
                        <div class="form-group">
                            <label>{{ customer.label }}</label>
                            {{ customer }}
                            <span style='color: red;'>{{ customer.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/add_edit_class_study.html
{% extends "base.html" %}
{% block con %}
    <section class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for class in class_list %}
                        <div class="form-group">
                            <label>{{ class.label }}</label>
                            {{ class }}
                            <span style='color: red;'>{{ class.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/add_edit_student_study.html
{% extends "base.html" %}
{% block con %}
    <section class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for student in student_list %}
                        <div class="form-group">
                            <label>{{ student.label }}</label>
                            {{ student }}
                            <span style='color: red;'>{{ student.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/add_track_customer.html
{% extends "base.html" %}
{% block con %}
    <section class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for customer in customer_list %}
                        <div class="form-group">
                            <label>{{ customer.label }}</label>
                            {{ customer }}
                            <span style='color: red;'>{{ customer.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/edit_customer.html
{% extends "base.html" %}
{% block con %}
    <section class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for customer in customer_list %}
                        <div class="form-group">
                            <label>{{ customer.label }}</label>
                            {{ customer }}
                            <span style='color: red;'>{{ customer.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/index.html
{% extends "base.html" %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--这两种引入方式，？？？-->
    <script src="/static/js/jquery.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
</head>
<body>
<h3>登录页面</h3>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">用户名</label>
                    <input type="text" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="">密码</label>
                    <input type="password" class="form-control" id="password">
                </div>
                <div class="form-group">
                    <label for="">验证码</label>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="validcode">
                        </div>
                        <div class="col-md-6">
                            <img width="350" height="38" src="/get_valid_img/" alt="" id="img">
                        </div>
                    </div>
                </div>
                <!--点击登陆，触发点击事件-->
                <input type="button" class="btn btn-primary pull-right login_btn" value="登录">
                <a href="/register/" class="btn btn-success pull-right">注册</a>
                <a href="/model_register/" class="btn btn-success pull-right">modelForm注册</a>
                <span class="error"></span>
            </form>
        </div>
    </div>
</div>
</body>
<script>
    $('.login_btn').click(function () {
        $.ajax({
            url: "",
            type: "post",
            data: {
                username: $('#username').val(),
                password: $('#password').val(),
                validcode: $('#validcode').val(),
                // csrf跨站请求伪造（注意：body标签中必须存在csrf_token）
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
            },
            success: function (response) {
                // ajax根据Content-Type 类型,自动把数据解开, 这里的response接收的就是处理后的对象
                console.log(response);
                if (response.username) {
                    // 登录成功
                    location.href="/index/"
                }else{
                    // 登录失败，显示错误信息
                    $('.error').html(response.err_msg).css('color','red')
                }
            }
        })
    });
    // 验证码刷新
    $("img").click(function(){
        // ？？？？？？
        this.src+="?"
    })
</script>
</html>

templates/model_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--这两种引入方式，？？？-->
    <script src="/static/js/jquery.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
</head>
<body>
<h3>登录页面</h3>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {% for filed in form %}
                <div class="form-group">
                    <label for="">{{ filed.label }}</label>
                    {{ filed }}
                    <span class="error pull-right"></span>
                </div>
                {% endfor %}
                <input type="button" class="btn btn-primary pull-left reg_btn" value="提交">
                <span class="error"></span>
            </form>
        </div>
    </div>
</div>
</body>
<script>
    $(".reg_btn").click(function(){
        $.ajax({
            url:"",
            type:"post",
            data:{
                username: $("#id_username").val(),
                password: $("#id_password").val(),
                r_password: $("#id_r_password").val(),
                email: $("#id_email").val(),
                csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val(),
            },
            success: function(response) {
                if (response.username) {
                    location.href = "/login/"
                } else {
                    // 清空原来的错误
                    // has-error 显示红色边框, bootstrap自带的类属性
                    $('.error').html('');
                    $('.form-group').removeClass("has-error");

                    // 展示新的错误
                    $.each(response.err_msg, function (i, j) {
                        console.log(i, j);
                        $("#id_" + i).next().html(j[0]).css("color", "red").parent().addClass("has-error");
                    })
                }
            }
        })
    })
</script>
</html>

templates/mycustomer_list.html
{% extends "base.html" %}
{% block con %}
    <section class="content-header">
        <form href="" class="pull-right">
            <ol class="breadcrumb">
                <!--知识点:
                vertical-align 微调元素
                form-control 会占一行, 要调成行内样式
                button 会将from里的数据组装成键值对
                -->
                <select name="field" class="form-control" style="display:inline-block; width: 100px; vertical-align: -1px;">
                    <option value="name">姓名</option>
                    <option value="qq">QQ</option>
                    <option value="phone">手机</option>
                </select>
                <input type="text" name="q" class="form-control" style="display: inline-block; width: 200px;">
                <button class="btn btn-primary" style="vertical-align: 0px;">go</button>
            </ol>
        </form>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">私有客户</h3>
                    </div>


                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>编号</th>
                                <th>客户姓名</th>
                                <th>性别</th>
                                <th>QQ</th>
                                <th>手机号</th>
                                <th>客户来源</th>
                                <th>咨询日期</th>
                                <th>当前状态</th>
                                <th>销售</th>
                                <th>所报班级</th>
                                <th>跟踪记录</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for customers in customers_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ customers.name }}</td>
                                    <td>{{ customers.get_sex_display }}</td>
                                    <td>{{ customers.qq }}</td>
                                    <td>{{ customers.phone }}</td>
                                    <td>{{ customers.get_source_display }}</td>
                                    <td>{{ customers.date|date:"Y-m-d" }}</td>
                                    <td>{{ customers.get_status_display }}</td>
                                    <td>{{ customers.consultant }}</td>
                                    <td>{{ customers.get_classlist }}</td>
                                    <td><a href="/customers/tracking/?customer_id={{ customers.pk }}">跟踪详情</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {{ pagination.page_html|safe }}
                            </ul>
                        </nav>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
{% endblock %}

templates/record_entry.html
{% extends "base.html" %}
{% block con %}
    <section class="content-header">
        <h1>
            班级学习记录
            <small>Optional description</small>
        </h1>
    </section>

    <!-- 批量处理form表单 -->
    <form action="" method="post">
        {% csrf_token %}
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <!-- /.box-header -->
                        <div class="box-body">
                            <!-- 这个没有为什么，一定要加 -->
                            {{ formset.management_form }}
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>编号</th>
                                    <th>姓名</th>
                                    <th>考勤</th>
                                    <th>成绩</th>
                                    <th>批语</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for form in formset %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <!--form.id 必须写，不然报：This field is required.-->
                                        {{ form.id }}
                                        <!--form.student
                                        这样写在这里，默认会渲染成下来菜单样式，
                                        如果不想要，可以写成form.instance.student，其它一样
                                        -->
                                        <td>{{ form.instance.student }}</td>
                                        <td>{{ form.instance.get_record_display }}</td>
                                        <td>{{ form.score }}</td>
                                        <td>{{ form.homework_note }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <button class="btn btn-primary" style="vertical-align: 0px;">提交</button>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
    </form>

{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--这两种引入方式，？？？-->
    <script src="/static/js/jquery.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
</head>
<body>
<h3>登录页面</h3>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="post">
                {% csrf_token %}
                {% for filed in form %}
                <div class="form-group">
                    <label for="">{{ filed.label }}</label>
                    {{ filed }}
                    <span class="error pull-right"></span>
                </div>
                {% endfor %}
                <input type="button" class="btn btn-primary pull-left reg_btn" value="提交">
                <span class="error"></span>
            </form>
        </div>
    </div>
</div>
</body>
<script>
    $(".reg_btn").click(function(){
        $.ajax({
            url:"",
            type:"post",
            data:{
                username: $("#id_username").val(),
                password: $("#id_password").val(),
                r_password: $("#id_r_password").val(),
                email: $("#id_email").val(),
                csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val(),
            },
            success: function(response) {
                if (response.username) {
                    location.href = "/login/"
                } else {
                    // 清空原来的错误
                    // has-error 显示红色边框, bootstrap自带的类属性
                    $('.error').html('');
                    $('.form-group').removeClass("has-error");

                    // 展示新的错误
                    $.each(response.err_msg, function (i, j) {
                        console.log(i, j);
                        $("#id_" + i).next().html(j[0]).css("color", "red").parent().addClass("has-error");
                    })
                }
            }
        })
    })
</script>
</html>